---
# If disktype is RAID we use the options:
# -f -K -i size=512 -d sw=%s,su=%sk -n size=8192 where sw is the diskcount and
# su is the stripe_unit_size
- name: Set XFS options for JBOD
  set_fact:
     fs_options: " -f -K -i size=512 -n size=8192 "

- name: Set XFS options for RAID devices
  set_fact:
     raid_options:
        " -d sw={{ gluster_infra_diskcount }},\
             su={{ gluster_infra_stripe_unit_size }}k "
  when: >
      gluster_infra_disktype == 'RAID6' or
      gluster_infra_disktype == 'RAID10'


# We support only XFS. Filesysem options sw, su are specific to XFS
- name: Create filesystem on thin logical vols
  filesystem:
     fstype: xfs
     dev: "/dev/{{ item.vgname }}/{{ item.lvname }}"
     opts: "{{ fs_options }} {{ raid_options | default('') }}"
     force: "{{ gluster_infra_fs_force | default('yes') }}"
  with_items: "{{ gluster_infra_lv_logicalvols }}"
  when: gluster_infra_lv_logicalvols is defined

- name: Create filesystem on thick logical vols
  filesystem:
     fstype: xfs
     dev: "/dev/{{ item.vgname }}/{{ item.lvname }}"
     opts: "{{ fs_options }} {{ raid_options | default('') }}"
     force: "{{ gluster_infra_fs_force | default('yes') }}"
  with_items: "{{ gluster_infra_thick_lvs }}"
  when: gluster_infra_thick_lvs is defined
