---
# tasks file for backend-reset
# unmount the directories

- name: unmount the directories (if mounted)
  mount:
    state: absent
    path: "{{ item }}"
  with_items: "{{ gluster_infra_reset_mnt_paths }}"
  when: gluster_infra_reset_mnt_paths is defined

# Delete the volume groups and physical volumes
- name: Delete volume groups
  lvg:
    vg: "{{ item }}"
    state: absent
    force: yes
  with_items: "{{ gluster_infra_reset_volume_groups }}"
  when: gluster_infra_reset_volume_groups is defined

# Remove vdo devices if any
#- name: Remove VDO devices
#  vdo:
#    name: "{{ item }}"
#    state: absent
#  with_items: "{{ gluster_infra_reset_vdos }}"
#  when: gluster_infra_reset_vdos is defined
