---
# defaults file for gluster.infra
# Defaults for firewall setup
gluster_infra_fw_permanent: true
gluster_infra_fw_state: enabled
gluster_infra_fw_zone: public

# Defaults for backend setup
gluster_infra_disktype: JBOD
#gluster_infra_vdo_state: present
#gluster_infra_lv_cachelvname: glusterfs_ssd_cache
# GlusterFS recommends 16G, if it has to be overridden set
# this variable in playbooks
