---
- name: Create a volume
  gluster_volume:
        state: "{{ gluster_cluster_state | default('present') }}"
        volume: "{{ gluster_cluster_volume }}"
        bricks: "{{ gluster_cluster_bricks }}"
        cluster: "{{ gluster_cluster_hosts }}"
        transport: "{{ gluster_cluster_transport | default('tcp') }}"
        replicas: "{{ gluster_cluster_replica_count | default(0) }}"
        arbiters: "{{ gluster_cluster_arbiter_count | default(0)}}"
        disperses: "{{ gluster_cluster_disperse_count | default(0) }}"
        redundancies: "{{ gluster_cluster_redundancy_count | default(0) }}"
        force: "{{ gluster_cluster_force | default('no') }}"
        options: "{{ gluster_cluster_options | default({}) }}"
  run_once: true
